spring:
  config:
    activate:
      on-profile: production
  r2dbc:
    url: r2dbc:postgresql://your-application-production.bneslso0f2t3c.us-east-1.rds.amazonaws.com:5432/postgres?sslMode=require
    username: postgres
    password: postgres

springdoc:
  swagger-ui:
    enabled: true
    path: v1/your-application/swagger-ui.html
  api-docs:
    path: /v1/your-application-docs